### PR TITLE
feat/562-support-for-absolute-cache-path

### PR DESCRIPTION
**Pull request by jszuminski**
Added #562, cache path option now supports absolute paths.

### CODE REVIEW

**Review by PaulDalek — APPROVED** [review]

**Comment by dylanlan** [comment]
I'm excited for this feature! Any ETA on when it might get merged & published?

**Comment by ddixon-bcs** [comment]
This would be such a useful feature. I would also love an ETA on when we could expect this to be released.

**Review by cvasseng — APPROVED** [review]

**Comment by wild-arctic-fox** [comment]
Hope this feature will allow use Highchart export server on lambda.  I would also like an ETA on when we could expect this to be released.

**Comment by dylanlan** [comment]
I'm still curious if there's any ETA for when this feature will get published to the NPM registry?

**Pull request merged**
