### PR TITLE
enhancement/tarn-based-resource-pool

### PR DESCRIPTION
**Pull request by PaulDalek**
Replaced the generic-pool with the tarn resources pool.

### CODE REVIEW

**Review by jakubSzuminski — APPROVED** [review]
LGTM!

The `http-tests` pass flawlessly (and, at least on my local machine, a little faster than with `generic-pool`). The `node-tests` and `cli-tests` also pass a little better than in the previous version with `generic-pool`.

**Review by jakubSzuminski — CHANGES_REQUESTED** [review]
I've pulled all the changes and ran the tests. While all the `cli-tests` pass flawlessly, I've noticed an error (which I believe did not appear before) when running `http-tests` (maybe it's my laptop's fault?): 

```
Mon Oct 09 2023 15:45:39 GMT+0200 [error] - [pool] Error when acquiring worker of an event id 25: TimeoutError: operation timed out for an unknown reason
    at C:\Users\Jakub\exporting\new-clone\node-export-server\node_modules\tarn\dist\PendingOperation.js:17:27
    at async postWork (file:///C:/Users/Jakub/exporting/new-clone/node-export-server/lib/pool.js:311:20)
Mon Oct 09 2023 15:45:39 GMT+0200 [error] - [export] Work: 76806a217dd143648666062693664b0e could not be completed, sending: In pool.postWork: [pool] Error when acquiring available entry: Error: operation timed out for an unknown reason
```

And the same error appears when running `node-tests` (for most of the tests).

Could these changes be related to this PR? Do you think it might be a hint to the memory leak issue?

**Comment by cvasseng** [comment]
I'm getting similar issues here:

```
Tue Oct 10 2023 10:44:16 GMT+0200 [notice] - [browser] attempting to get a browser instance (try 0)
Tue Oct 10 2023 10:44:16 GMT+0200 [notice] - [browser] failed: Error: Failed to launch the browser process! undefined
[53175:53175:1010/104416.058855:ERROR:process_singleton_posix.cc(335)] Failed to create /home/xxx/node-export-server/tmp/SingletonLock: File exists (17)


TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at ChildProcess.onClose (file:///node-export-server/node_modules/@puppeteer/browsers/lib/esm/launch.js:268:24)
    at ChildProcess.emit (node:events:526:35)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
```

**Comment by cvasseng** [comment]
There's a problem on Linux where it doesn't exit cleanly anymore, which causes locks to be stuck in limbo (which again makes it impossible to restart it without manually deleting the locks).

Likely related to exit listeners and pool shutdown.

**Review by jakubSzuminski — APPROVED** [review]
The timeout in tests seems to be unrelated to this PR, but more to my personal machine I was running the server on.

**Review by cvasseng — APPROVED** [review]

**Comment by jakubSzuminski** [comment]
Let's merge it and see if it solves the other issues?

**Pull request merged**
