### PR TITLE
health/moving-average-indicator

### PR DESCRIPTION
**Pull request by jszuminski**
Added a health-moving-average endpoint.

### CODE REVIEW

**Review by PaulDalek — APPROVED** [review]
Good work!

**Comment by jakubSzuminski** [comment]
1. Currently, the sum of `success` and `failure` is lower than the entire pool work count.
2. Also add a moving average for an hour.

**Review by PaulDalek — APPROVED** [review]
Good work! The only thing is that instead of using separate functions for every stat, I would create one function that returns everything.

**Comment by jszuminski** [comment]
You're right, I'm on it.

**Review by PaulDalek — APPROVED** [review]
Good work!

**Pull request merged**
