### PR TITLE
puppeteer/module-bundler

### PR DESCRIPTION
**Pull request by jakubSzuminski**
# Goals 
The main goal of this pull request is to add an intuitive module bundler with basic configuration which will allow us to serve minifed files to the users, supporting both `ES` and `CommonJS` standard of ECMAScript. Additionally, I'll add `husky` with a simple `pre-commit` hook which will: check eslint of the code, run basic tests, build the project.

# Tasks
- [x] add `rollup`
- [x] add building to both `es` and `cjs`
- [x] set the proper default export path in `package.json`
- [x] add a proper configuration for rollup
- [x] add pre-commit hook to build the project
- [x] add a note to the readme.md

### CODE REVIEW

**Comment by jakubSzuminski** [comment]
There seems to be a problem with the `node-fetch` package which offers no support for CommonJS. The ESM version, however, works as expected.

**Comment by jakubSzuminski** [comment]
The approach that is currently implemented here is the following:
- before the commit, the `pre-commit` hook is ran which builts the minified files and adds them to the staged changes in git

There is, hovewer, a big problem that I've just thought of with this approach as it can cause code conflicts difficult to solve. I think that `dist/` maybe should be ignored by git via `.gitignore`? 

It may be worth considering adding a [`standard-version`](https://www.npmjs.com/package/standard-version) or other packages to:
- update the changelog automatically
- update the package version in `package.json`
- build the project and add the `dist/` to staged files

What do you guys think? @cvasseng @PaulDalek

**Review by PaulDalek — APPROVED** [review]
Looks good, great work!

**Comment by jakubSzuminski** [comment]
When it comes to our discussion about building the distribution directory, I've created a separate issue for this: https://github.com/highcharts/node-export-server/issues/430

For now, I think, it's most important to focus on getting the prioritized issues done and releasing this version.

**Pull request merged**
