### PR TITLE
enhancement/readme-and-changelog-update

### PR DESCRIPTION
**Pull request by PaulDalek**
Updated README, CHANGELOG and Puppeteer version.

### CODE REVIEW

**Review by jszuminski — APPROVED** [review]
LGTM!

**Comment by bvogel** [comment]
Question: the README now mentions "The v4 introduces numerous breaking changes", however the CHANGELOG only has `New Features`,  `Enhancements` and `Fixes`. Could the CHANGELOG please clearly mark what changes are breaking?

**Comment by bvogel** [comment]
After reading the CHANGELOG several times, are these the breaking changes:
```
- Changed the customCode section of options to customLogic in order to avoid confusion with the existing customCode property within.
- Renamed the environment variables for a better representation of their roles (refer to all envs in the README's Environment Variables section).
- Renamed the HIGHCHARTS_MODULES and HIGHCHARTS_INDICATORS environment variables respectively to HIGHCHARTS_MODULE_SCRIPTS and HIGHCHARTS_INDICATOR_SCRIPTS.
- Renamed the scripts property of the config options to customScripts.
- Renamed the initPool function to initExport in the main module.
- Renamed the init function to initPool in the pool module.
- Renamed the environment variable POOL_LISTEN_TO_PROCESS_EXITS to OTHER_LISTEN_TO_PROCESS_EXITS.
- Moved the listenToProcessExits from the pool to the other section of the options.
```

If so, I don't think many uses will be affected, however they should be their own section in the changelog?

**Comment by PaulDalek** [comment]
@bvogel Most of the breaking changes relate to name changing of some properties and envs, yes. But there are also many others included in CHANGELOG.

> I don't think many users will be affected

Probably but some might be, therefore the info.

**Comment by bvogel** [comment]
As we a currently affected by #523 in our production system - how far away are we from a new (beta/rc) release? If there is no immediate time plan we might want to look to use the current `master`/`main` branch as gem (which we really don't want to do...)

**Pull request merged**
