### PR TITLE
enhancement/added-browser-shell-flag

### PR DESCRIPTION
**Pull request by PaulDalek**
Added the browserShellMode option.

### CODE REVIEW

**Comment by bvogel** [comment]
Any news of the next release?

**Comment by bvogel** [comment]
bump!

**Comment by jszuminski** [comment]
@bvogel We're getting closer to the release. The performance of v4.0.0 compared to v3 has drastically improved. Hopefully, it will be out in ~2 weeks (unless any new serious problems related to v4.0.0 arise).

**Comment by bvogel** [comment]
Thank you so much for the update!

**Pull request merged**
